package kr.co.aim.common.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum MessageList {
    ALARM_REPORT("AlarmReport"),
    CONNECTION_CHECK("ConnectionCheck"),
    CONNECTION("Connection"),
    ARE_YOU_THERE_REPLY("AreYouThereReply"),
    ARE_YOU_THERE_REQUEST("AreYouThereRequest"),
    ORDER_CREATE_REQUEST("OrderCreateRequest"),
    RECIPE_REQUEST("RecipeRequest"),
    RECIPE_REPLY("RecipeReply"),
    ZONE_REQUEST("ZoneRequest"),
    ZONE_REPLY("ZoneReply"),
    ORDER_RELEASE_REQUEST("OrderReleaseRequest"),
    ORDER_RELEASE_REPLY("OrderReleaseReply"),
    MATERIAL_ASSIGN_CARRIER_REQUEST("MaterialAssignCarrierRequest"),
    MATERIAL_ASSIGN_CARRIER_REPLY("MaterialAssignCarrierReply"),
    CARRIER_IN_WAREHOUSE("CarrierInWarehouse"),
    CARRIER_OUT_WAREHOUSE("CarrierOutWarehouse"),
    CARRIER_SYNCHRONIZATION_REQUEST("CarrierSynchronizationRequest"),
    CARRIER_SYNCHRONIZATION_REPLY("CarrierSynchronizationReply"),
    LOAD_COMPLETE("LoadComplete"),
    LOAD_REQUEST("LoadRequest"),
    CARRIER_DISPATCH_REQUEST("CarrierDispatchRequest"),
    DESTINATION_DISPATCH_REQUEST("DestinationDispatchRequest"),
    UNLOAD_COMPLETE("UnloadComplete"),
    UNLOAD_REQUEST("UnloadRequest"),
    OP_CALL_SEND("OpCallSend"),
    COMMUNICATION_STATE_REPORT("CommunicationStateReport"),
    COMMUNICATION_STATE_CHANGED("CommunicationStateChanged"),
    EQUIPMENT_STATE_REPORT("EquipmentStateReport"),
    EQUIPMENT_STATE_CHANGED("EquipmentStateChanged"),
    PORT_STATE_REPORT("PortStateReport"),
    PORT_TYPE_CHANGED("PortTypeChanged"),
    PORT_USE_TYPE_CHANGED("PortUseTypeChanged"),
    PORT_STATE_CHANGED("PortStateChanged"),
    TRANSPORT_ORDER_VALIDATION_REQUEST("TransportJobValidationRequest"),
    TRANSPORT_JOB_VALIDATION_REQUEST("TransportJobValidationRequest"),
    TRANSPORT_JOB_VALIDATION_REPLY("TransportJobValidationReply"),
    TRANSPORT_JOB_REQUEST_BY_WMS("TransportJobRequestByWMS"),
    TRANSPORT_JOB_REPLY_BY_WMS("TransportJobReplyByWMS"),
    TRANSPORT_JOB_REQUEST("TransportJobRequest"),
    TRANSPORT_ORDER_REQUEST("TransportOrderRequest"),
    TRANSPORT_JOB_REPLY("TransportJobReply"),
    TRANSPORT_JOB_STARTED("TransportJobStarted"),
    TRANSPORT_JOB_COMPLETED("TransportJobCompleted"),
    TAKE_OFF_CARRIER("TakeOffCarrier"),
    CARRIER_LOCATION_CHANGED("CarrierLocationChanged"),
    CARRIER_BLOCKED("CarrierBlocked"),
    CARRIER_UNBLOCKED("CarrierUnblocked"),
    TRANSPORT_JOB_CANCEL_STARTED("TransportJobCancelStarted"),
    TRANSPORT_JOB_CANCEL_COMPLETED("TransportJobCancelCompleted"),
    TRANSPORT_JOB_CANCEL_FAILED("TransportJobCancelFailed"),
    DESTINATION_CHANGED("DestinationChanged"),
    ACTIVE_TRANSPORT_JOB_REPORT("ActiveTransportJobReport"),
    INVENTORY_CARRIER_DATA_REPORT("InventoryCarrierDataReport"),
    INVENTORY_ZONE_DATA_REPORT("InventoryZoneDataReport"),
    DESTINATION_REQUEST("DestinationRequest"),
    DESTINATION_REPLY("DestinationReply"),
    CARRIER_DATA_REPORT("CarrierDataReport"),
    CARRIER_DATA_INSTALLED("CarrierDataInstalled"),
    CARRIER_DATA_REMOVED("CarrierDataRemoved"),
    OPERATION_MODE_REPORT("OperationModeReport"),
    OPERATION_MODE_CHANGED("OperationModeChanged"),
    PORT_TRANSPORT_MODE_CHANGED("PortTransportModeChanged"),
    CARRIER_SCANNED("CarrierScanned"),
    CARRIER_CLEAN_JOB_STARTED("CarrierCleanJobStarted"),
    CARRIER_CLEAN_JOB_CANCELED("CarrierCleanJobCanceled"),
    CARRIER_CLEAN_JOB_ENDED("CarrierCleanJobEnded"),
    CARRIER_VALIDATION_REQUEST("CarrierValidationRequest"),
    CARRIER_VALIDATION_REPLY("CarrierValidationReply"),
    CARRIER_INFO_DOWNLOAD_SEND("CarrierInfoDownloadSend"),
    CARRIER_INFO_DOWNLOAD_SEND_REPLY("CarrierInfoDownloadSendReply"),
    CARRIER_UNASSIGNED("CarrierUnassigned"),
    MATERIAL_DEASSIGNED_FROM_CARRIER("MaterialDeassignedFromCarrier"),
    PROCESS_JOB_STARTED("ProcessJobStarted"),
    PROCESS_JOB_ABORTED("ProcessJobAborted"),
    PROCESS_JOB_DATA_REPORT("ProcessJobDataReport"),
    PROCESS_JOB_ENDED("ProcessJobEnded"),
    MATERIAL_ASSIGNED_TO_CARRIER("MaterialAssignedToCarrier"),
    INSERT_EVENT_QUEUE_REPORT("InsertEventQueueReport"),
    POWDER_EVENT_QUEUE_REPORT("PowderEventQueueReport"),
    WHAT_NEXT("WhatNext"),
    WHERE_NEXT("WhereNext");


    private final String messageName;
}