create sql

-- DEF
CREATE DATABASE NEXBEDEF;

USE NEXBEDEF;

CREATE TABLE CARRIER_DEF (
                             ID                             bigint               NOT NULL,
                             CARRIER_DEF_NAME               varchar(40)          NULL,
                             FACTORY_NAME                   varchar(40)          NOT NULL,
                             DESCRIPTION                    varchar(400)         NULL,
                             CARRIER_TYPE                   varchar(40)          NULL,
                             CARRIER_DETAIL_TYPE            varchar(40)          NULL,
                             DEFAULT_CAPACITY               int                  NULL,
                             USE_COUNT_LIMIT                int                  NULL,
                             USE_DURATION_LIMIT             int                  NULL,
                             COUNT_LIMIT_PER_CLEAN          int                  NULL,
                             DURATION_LIMIT_PER_CLEAN       int                  NULL,
                             CLEAN_COUNT_LIMIT              int                  NULL,
                             CHECK_OUT_STATE                varchar(40)          NULL,
                             CHECK_OUT_TIME                 datetime2            NULL,
                             CHECK_OUT_USER                 varchar(40)          NULL,
                             DATA_STATE                     varchar(40)          NULL,
                             EVENT_NAME                     varchar(40)          NULL,
                             EVENT_TIME                     datetime2            NULL,
                             EVENT_USER                     varchar(40)          NULL,
                             EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE CARRIER_DEF_HISTORY (
                                     ID                             bigint               NOT NULL,
                                     CARRIER_DEF_NAME               varchar(40)          NULL,
                                     FACTORY_NAME                   varchar(40)          NOT NULL,
                                     DESCRIPTION                    varchar(400)         NULL,
                                     CARRIER_TYPE                   varchar(40)          NULL,
                                     CARRIER_DETAIL_TYPE            varchar(40)          NULL,
                                     DEFAULT_CAPACITY               int                  NULL,
                                     USE_COUNT_LIMIT                int                  NULL,
                                     USE_DURATION_LIMIT             int                  NULL,
                                     COUNT_LIMIT_PER_CLEAN          int                  NULL,
                                     DURATION_LIMIT_PER_CLEAN       int                  NULL,
                                     CLEAN_COUNT_LIMIT              int                  NULL,
                                     CHECK_OUT_STATE                varchar(40)          NULL,
                                     CHECK_OUT_TIME                 datetime2            NULL,
                                     CHECK_OUT_USER                 varchar(40)          NULL,
                                     DATA_STATE                     varchar(40)          NULL,
                                     EVENT_NAME                     varchar(40)          NULL,
                                     EVENT_TIME                     datetime2            NULL,
                                     EVENT_USER                     varchar(40)          NULL,
                                     EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE EQUIPMENT_DEF (
                               ID                             bigint               NOT NULL,
                               EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                               FACTORY_NAME                   varchar(40)          NOT NULL,
                               DESCRIPTION                    varchar(400)         NULL,
                               EQUIPMENT_TYPE                 varchar(40)          NULL,
                               EQUIPMENT_GROUP_NAME           varchar(32)          NULL,
                               DETAIL_EQUIPMENT_TYPE          varchar(40)          NULL,
                               VENDOR_ID                      varchar(40)          NULL,
                               MODEL_ID                       varchar(40)          NULL,
                               PROCESS_CAPACITY               int                  NULL,
                               CONTAINER_TYPE                 varchar(40)          NULL,
                               PLC_TYPE                       varchar(40)          NULL,
                               ROUTE_KEY                      varchar(40)          NULL,
                               SERVER_NAME                    varchar(40)          NULL,
                               CHECK_OUT_STATE                varchar(40)          NULL,
                               CHECK_OUT_TIME                 datetime2            NULL,
                               CHECK_OUT_USER                 varchar(40)          NULL,
                               DATA_STATE                     varchar(40)          NULL,
                               LOCAL_NO                       int                  NOT NULL,
                               EVENT_NAME                     varchar(40)          NULL,
                               EVENT_TIME                     datetime2            NULL,
                               EVENT_USER                     varchar(40)          NULL,
                               EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE EQUIPMENT_DEF_HISTORY (
                                       ID                             bigint               NOT NULL,
                                       EQUIPMENT_NAME                 varchar(30)          NOT NULL,
                                       FACTORY_NAME                   varchar(40)          NOT NULL,
                                       DESCRIPTION                    varchar(400)         NULL,
                                       EQUIPMENT_TYPE                 varchar(40)          NULL,
                                       EQUIPMENT_GROUP_NAME           varchar(40)          NULL,
                                       DETAIL_EQUIPMENT_TYPE          varchar(40)          NULL,
                                       VENDOR_ID                      varchar(40)          NULL,
                                       MODEL_ID                       varchar(40)          NULL,
                                       PROCESS_CAPACITY               int                  NULL,
                                       CONTAINER_TYPE                 varchar(40)          NULL,
                                       PLC_TYPE                       varchar(40)          NULL,
                                       ROUTE_KEY                      varchar(40)          NULL,
                                       SERVER_NAME                    varchar(40)          NULL,
                                       CHECK_OUT_STATE                int                  NOT NULL,
                                       CHECK_OUT_TIME                 varchar(40)          NULL,
                                       CHECK_OUT_USER                 datetime2            NOT NULL,
                                       DATA_STATE                     varchar(40)          NULL,
                                       LOCAL_NO                       int                  NOT NULL,
                                       EVENT_NAME                     varchar(40)          NULL,
                                       EVENT_TIME                     datetime2            NULL,
                                       EVENT_USER                     varchar(40)          NULL,
                                       EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE EQUIPMENT_GROUP_DEF (
                                     ID                             bigint               NOT NULL,
                                     EQUIPMENT_GROUP_NAME           varchar(40)          NOT NULL,
                                     DESCRIPTION                    varchar(400)         NULL,
                                     CHECK_OUT_STATE                varchar(40)          NULL,
                                     CHECK_OUT_TIME                 datetime2            NULL,
                                     CHECK_OUT_USER                 varchar(40)          NULL,
                                     DATA_STATE                     varchar(40)          NULL,
                                     EVENT_NAME                     varchar(40)          NULL,
                                     EVENT_TIME                     datetime2            NULL,
                                     EVENT_USER                     varchar(40)          NULL,
                                     EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE EQUIPMENT_GROUP__DEF_HISTORY (
                                              ID                             bigint               NOT NULL,
                                              EQUIPMENT_GROUP_NAME           varchar(40)          NOT NULL,
                                              DESCRIPTION                    varchar(400)         NULL,
                                              CHECK_OUT_STATE                varchar(40)          NULL,
                                              CHECK_OUT_TIME                 datetime2            NULL,
                                              CHECK_OUT_USER                 varchar(40)          NULL,
                                              DATA_STATE                     varchar(40)          NULL,
                                              EVENT_NAME                     varchar(40)          NULL,
                                              EVENT_TIME                     datetime2            NOT NULL,
                                              EVENT_USER                     varchar(40)          NULL,
                                              EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE PORT_DEF (
                          ID                             bigint               NOT NULL,
                          EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                          PORT_NAME                      varchar(40)          NOT NULL,
                          FACTORY_NAME                   varchar(40)          NOT NULL,
                          PORT_NUMBER                    int                  NULL,
                          DESCRIPTION                    varchar(400)         NULL,
                          TRANSPORT_MODE                 varchar(40)          NULL,
                          PORT_TYPE                      varchar(40)          NULL,
                          DETAIL_PORT_TYPE               varchar(40)          NULL,
                          PORT_USE_TYPE                  varchar(40)          NULL,
                          PORT_ROLE_TYPE                 varchar(40)          NULL,
                          WORK_CENTER_NAME               varchar(40)          NULL,
                          LOCATION_ID                    varchar(40)          NULL,
                          CONNECTED_EQUIPMENT_NAME       varchar(40)          NULL,
                          CONNECTED_PORT_NAME            varchar(40)          NULL,
                          LOAD_REQUEST_YN                varchar(5)           NULL,
                          UNLOAD_REQUEST_YN              varchar(5)           NULL,
                          CHECK_OUT_STATE                varchar(40)          NULL,
                          CHECK_OUT_TIME                 datetime2            NULL,
                          CHECK_OUT_USER                 varchar(40)          NULL,
                          DATA_STATE                     varchar(40)          NULL,
                          EVENT_NAME                     varchar(40)          NULL,
                          EVENT_TIME                     datetime2            NULL,
                          EVENT_USER                     varchar(40)          NULL,
                          EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE PORT_DEF_HISTORY (
                                  ID                             bigint               NOT NULL,
                                  EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                                  PORT_NAME                      varchar(40)          NOT NULL,
                                  FACTORY_NAME                   varchar(40)          NOT NULL,
                                  PORT_NUMBER                    int                  NULL,
                                  DESCRIPTION                    varchar(400)         NULL,
                                  TRANSPORT_MODE                 varchar(40)          NULL,
                                  PORT_TYPE                      varchar(40)          NULL,
                                  DETAIL_PORT_TYPE               varchar(40)          NULL,
                                  PORT_USE_TYPE                  varchar(40)          NULL,
                                  PORT_ROLE_TYPE                 varchar(40)          NULL,
                                  WORK_CENTER_NAME               varchar(40)          NULL,
                                  LOCATION_ID                    varchar(40)          NULL,
                                  CONNECTED_EQUIPMENT_NAME       varchar(40)          NULL,
                                  CONNECTED_PORT_NAME            varchar(40)          NULL,
                                  LOAD_REQUEST_YN                varchar(5)           NULL,
                                  UNLOAD_REQUEST_YN              varchar(5)           NULL,
                                  CHECK_OUT_STATE                varchar(40)          NULL,
                                  CHECK_OUT_TIME                 datetime2            NULL,
                                  CHECK_OUT_USER                 varchar(40)          NULL,
                                  DATA_STATE                     varchar(40)          NULL,
                                  EVENT_NAME                     varchar(40)          NULL,
                                  EVENT_TIME                     datetime2            NULL,
                                  EVENT_USER                     varchar(40)          NULL,
                                  EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE PRODUCT_DEF (
                             ID                             bigint               NOT NULL,
                             PRODUCT_DEF_NAME               varchar(40)          NULL,
                             FACTORY_NAME                   varchar(40)          NOT NULL,
                             DESCRIPTION1                   varchar(100)         NULL,
                             DESCRIPTION2                   varchar(100)         NULL,
                             RATIO                          NUMERIC(15 , 4)      NULL,
                             DEFAULT_RECEIVE_QUANTITY       NUMERIC(15 , 3)      NULL,
                             TOLERANCE_VAL                  NUMERIC(15 , 4)      NULL,
                             EVENT_NAME                     varchar(40)          NULL,
                             EVENT_TIME                     datetime2            NULL,
                             EVENT_USER                     varchar(40)          NULL,
                             EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE PRODUCT_DEF_HISTORY (
                                     ID                             bigint               NOT NULL,
                                     PRODUCT_DEF_NAME               varchar(40)          NULL,
                                     FACTORY_NAME                   varchar(40)          NOT NULL,
                                     DESCRIPTION1                   varchar(100)         NULL,
                                     DESCRIPTION2                   varchar(100)         NULL,
                                     RATIO                          NUMERIC(15 , 4)      NULL,
                                     DEFAULT_RECEIVE_QUANTITY       NUMERIC(15 , 3)      NULL,
                                     TOLERANCE_VAL                  NUMERIC(15 , 4)      NULL,
                                     EVENT_NAME                     varchar(40)          NULL,
                                     EVENT_TIME                     datetime2            NULL,
                                     EVENT_USER                     varchar(40)          NULL,
                                     EVENT_COMMENT                  varchar(100)         NULL
);

-- DEF

-- MNG
CREATE DATABASE NEXBEMNG;

use NEXBEMNG;

CREATE TABLE shedlock(name VARCHAR(64) NOT NULL, lock_until datetime2 NOT NULL,
                      locked_at datetime2 NOT NULL, locked_by VARCHAR(255) NOT NULL, PRIMARY KEY (name));

CREATE TABLE CARRIER (
                         ID                             bigint               NOT NULL,
                         CARRIER_NAME                   varchar(40)          NOT NULL,
                         CARRIER_DEF_NAME               bigint               NULL,
                         CARRIER_STATE                  varchar(40)          NULL,
                         EQUIPMENT_NAME                 varchar(40)          NULL,
                         PORT_NAME                      varchar(40)          NULL,
                         ZONE_NAME                      varchar(40)          NULL,
                         POSITION_TYPE_NAME             varchar(40)          NULL,
                         POSITION_NAME                  varchar(40)          NULL,
                         CAPACITY                       int                  NULL,
                         CLEAN_STATE                    varchar(40)          NULL,
                         TRANSPORT_STATE                varchar(40)          NULL,
                         TRANSPORT_JOB_ID               bigint               NULL,
                         HOLD_STATE                     varchar(40)          NULL,
                         REASON_CODE                    varchar(40)          NULL,
                         USE_STATE                      varchar(40)          NULL,
                         USE_COUNT                      int                  NULL,
                         USE_COUNT_PER_CLEAN            int                  NULL,
                         CLEAN_COUNT                    int                  NULL,
                         QUANTITY                       NUMERIC(15 , 3)      NULL,
                         GAL_QUANTITY                   NUMERIC(15 , 3)      NULL,
                         LAST_CLEAN_TIME                datetime2            NULL,
                         CREATE_TIME                    datetime2            NULL,
                         INBOUND_TIME                   datetime2            NULL,
                         OUTBOUND_TIME                  datetime2            NULL,
                         CONTAINER_TYPE                 varchar(40)          NULL,
                         EVENT_NAME                     varchar(40)          NULL,
                         EVENT_TIME                     datetime2            NULL,
                         EVENT_USER                     varchar(40)          NULL,
                         EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE CARRIER_HISTORY (
                                 ID                             bigint               NOT NULL,
                                 CARRIER_NAME                   varchar(40)          NOT NULL,
                                 CARRIER_DEF_NAME               bigint               NULL,
                                 CARRIER_STATE                  varchar(40)          NULL,
                                 EQUIPMENT_NAME                 varchar(40)          NULL,
                                 PORT_NAME                      varchar(40)          NULL,
                                 ZONE_NAME                      varchar(40)          NULL,
                                 POSITION_TYPE_NAME             varchar(40)          NULL,
                                 POSITION_NAME                  varchar(40)          NULL,
                                 CAPACITY                       int                  NULL,
                                 CLEAN_STATE                    varchar(40)          NULL,
                                 TRANSPORT_STATE                varchar(40)          NULL,
                                 TRANSPORT_JOB_ID               bigint               NULL,
                                 HOLD_STATE                     varchar(40)          NULL,
                                 REASON_CODE                    varchar(40)          NULL,
                                 USE_STATE                      varchar(40)          NULL,
                                 USE_COUNT                      int                  NULL,
                                 USE_COUNT_PER_CLEAN            int                  NULL,
                                 CLEAN_COUNT                    int                  NULL,
                                 QUANTITY                       NUMERIC(15 , 3)      NULL,
                                 GAL_QUANTITY                   NUMERIC(15 , 3)      NULL,
                                 LAST_CLEAN_TIME                datetime2            NULL,
                                 CREATE_TIME                    datetime2            NULL,
                                 INBOUND_TIME                   datetime2            NULL,
                                 OUTBOUND_TIME                  datetime2            NULL,
                                 CONTAINER_TYPE                 varchar(40)          NULL,
                                 EVENT_NAME                     varchar(40)          NULL,
                                 EVENT_TIME                     datetime2            NULL,
                                 EVENT_USER                     varchar(40)          NULL,
                                 EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE EQUIPMENT (
                           ID                             bigint               NOT NULL,
                           EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                           PARENT_EQUIPMENT_ID            bigint               NULL,
                           EQUIPMENT_LEVEL                varchar(40)          NULL,
                           EQUIPMENT_STATE                varchar(40)          NULL,
                           COMMUNICATION_STATE            varchar(40)          NULL,
                           LOADING_COUNT                  NUMERIC(15 , 3)      NULL,
                           PROCESS_COUNT                  NUMERIC(15 , 3)      NULL,
                           RECIPE_NAME                    varchar(40)          NULL,
                           HOLD_STATE                     varchar(40)          NULL,
                           REASON_CODE                    varchar(40)          NULL,
                           RESOURCE_STATE                 varchar(40)          NULL,
                           OPERATION_MODE                 varchar(40)          NULL,
                           MESSAGE_SERVICE_ADDRESS        varchar(40)          NULL,
                           EVENT_NAME                     varchar(40)          NULL,
                           EVENT_TIME                     datetime2            NULL,
                           EVENT_USER                     varchar(40)          NULL,
                           EVENT_COMMENT                  varchar(100)         NULL,
                           PRODUCTION_ORDER_ID            bigint               NULL
);

CREATE TABLE EQUIPMENT_HISTORY (
                                   ID                             bigint               NOT NULL,
                                   EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                                   PARENT_EQUIPMENT_ID            bigint               NULL,
                                   EQUIPMENT_LEVEL                varchar(40)          NULL,
                                   EQUIPMENT_STATE                varchar(40)          NULL,
                                   COMMUNICATION_STATE            varchar(40)          NULL,
                                   LOADING_COUNT                  NUMERIC(15 , 3)      NULL,
                                   PROCESS_COUNT                  NUMERIC(15 , 3)      NULL,
                                   RECIPE_NAME                    varchar(40)          NULL,
                                   HOLD_STATE                     varchar(40)          NULL,
                                   REASON_CODE                    varchar(40)          NULL,
                                   RESOURCE_STATE                 varchar(40)          NULL,
                                   OPERATION_MODE                 varchar(40)          NULL,
                                   MESSAGE_SERVICE_ADDRESS        varchar(40)          NULL,
                                   EVENT_NAME                     varchar(40)          NULL,
                                   EVENT_TIME                     datetime2            NULL,
                                   EVENT_USER                     varchar(40)          NULL,
                                   EVENT_COMMENT                  varchar(100)         NULL,
                                   PRODUCTION_ORDER_ID            bigint               NULL
);

CREATE TABLE IF_EVENT_QUEUE (
                                ID                             bigint               NOT NULL,
                                EVENT_TYPE                     varchar(40)          NULL,
                                PAYLOAD                        varchar(4000)        NULL,
                                IF_STATUS                      varchar(40)          NULL,
                                CARRIER_NAME                   varchar(40)          NULL,
                                IDOC_ID                        bigint               NULL,
                                ORDER_ID                       varchar(40)          NULL,
                                ORDER_LINE_NUMBER              varchar(40)          NULL,
                                RETRY_CNT                      int                  NULL,
                                ERR_MSG                        varchar(400)         NULL,
                                CREATE_TIME                    datetime2            NULL,
                                UPDATE_TIME                    datetime2            NULL
);

CREATE TABLE LOT (
                     ID                             bigint               NOT NULL,
                     LOT_NAME                       varchar(40)          NULL,
                     ORIGINAL_LOT_NAME              varchar(40)          NULL,
                     LOT_STATUS                     varchar(40)          NULL,
                     ITEM_ID                        varchar(40)          NULL,
                     TOTAL_QUANTITY                 NUMERIC(15 , 3)      NULL,
                     HOLD_STATE                     varchar(40)          NULL,
                     REASON_CODE                    varchar(40)          NULL,
                     EVENT_NAME                     varchar(40)          NULL,
                     EVENT_TIME                     datetime2            NULL,
                     EVENT_USER                     varchar(40)          NULL,
                     EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE LOT_CARRIER_MAPPING (
                                     ID                             bigint               NOT NULL,
                                     LOT_NAME                       varchar(40)          NULL,
                                     CARRIER_NAME                   varchar(40)          NULL,
                                     ORDER_ID                       varchar(40)          NULL,
                                     ORDER_LINE_NUMBER              varchar(40)          NULL,
                                     PRODUCTION_ORDER_ID            bigint               NULL,
                                     SEQ                            int                  NULL,
                                     PRODUCTION_STATUS              varchar(40)          NULL,
                                     PROCESS_STATUS                 varchar(40)          NULL,
                                     QUANTITY                       NUMERIC(15 , 3)      NULL,
                                     GAL_QUANTITY                   NUMERIC(15 , 3)      NULL,
                                     MNG_KEY                        bigint               NULL,
                                     VALIDATION_TIME                datetime2            NULL,
                                     JOB_START_TIME                 datetime2            NULL,
                                     JOB_END_TIME                   datetime2            NULL,
                                     MANTI_REQUEST_STATE            varchar(40)          NULL,
                                     MANTI_REQUEST_TIME             datetime2            NULL,
                                     MANTI_REPLY_TIME               datetime2            NULL,
                                     RRN_REQUEST_STATE              varchar(40)          NULL,
                                     RRN_REQUEST_TIME               datetime2            NULL,
                                     RRN_REPLY_TIME                 datetime2            NULL,
                                     NEXT_EQUIPMENT_NAME            varchar(40)          NULL,
                                     HOLD_STATE                     varchar(40)          NULL,
                                     REASON_CODE                    varchar(40)          NULL,
                                     EVENT_NAME                     varchar(40)          NULL,
                                     EVENT_TIME                     datetime2            NULL,
                                     EVENT_USER                     varchar(40)          NULL,
                                     EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE LOT_CARRIER_MAPPING_HISTORY (
                                             ID                             bigint               NOT NULL,
                                             LOT_NAME                       varchar(40)          NULL,
                                             CARRIER_NAME                   varchar(40)          NULL,
                                             ORDER_ID                       varchar(40)          NULL,
                                             ORDER_LINE_NUMBER              varchar(40)          NULL,
                                             PRODUCTION_ORDER_ID            bigint               NULL,
                                             SEQ                            int                  NULL,
                                             PRODUCTION_STATUS              varchar(40)          NULL,
                                             PROCESS_STATUS                 varchar(40)          NULL,
                                             QUANTITY                       NUMERIC(15 , 3)      NULL,
                                             GAL_QUANTITY                   NUMERIC(15 , 3)      NULL,
                                             MNG_KEY                        bigint               NULL,
                                             VALIDATION_TIME                datetime2            NULL,
                                             JOB_START_TIME                 datetime2            NULL,
                                             JOB_END_TIME                   datetime2            NULL,
                                             MANTI_REQUEST_STATE            varchar(40)          NULL,
                                             MANTI_REQUEST_TIME             datetime2            NULL,
                                             MANTI_REPLY_TIME               datetime2            NULL,
                                             RRN_REQUEST_STATE              varchar(40)          NULL,
                                             RRN_REQUEST_TIME               datetime2            NULL,
                                             RRN_REPLY_TIME                 datetime2            NULL,
                                             NEXT_EQUIPMENT_NAME            varchar(40)          NULL,
                                             HOLD_STATE                     varchar(40)          NULL,
                                             REASON_CODE                    varchar(40)          NULL,
                                             EVENT_NAME                     varchar(40)          NULL,
                                             EVENT_TIME                     datetime2            NULL,
                                             EVENT_USER                     varchar(40)          NULL,
                                             EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE LOT_HISTORY (
                             ID                             bigint               NOT NULL,
                             LOT_NAME                       varchar(40)          NULL,
                             ORIGINAL_LOT_NAME              varchar(40)          NULL,
                             LOT_STATUS                     varchar(40)          NULL,
                             ITEM_ID                        varchar(40)          NULL,
                             TOTAL_QUANTITY                 NUMERIC(15 , 3)      NULL,
                             HOLD_STATE                     varchar(40)          NULL,
                             REASON_CODE                    varchar(40)          NULL,
                             EVENT_NAME                     varchar(40)          NULL,
                             EVENT_TIME                     datetime2            NULL,
                             EVENT_USER                     varchar(40)          NULL,
                             EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE PORT (
                      ID                             bigint               NOT NULL,
                      EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                      PORT_NAME                      varchar(40)          NOT NULL,
                      PORT_TYPE                      varchar(40)          NULL,
                      DESCRIPTION                    varchar(400)         NULL,
                      CONNECTED_STOCKER              varchar(40)          NULL,
                      TRANSPORT_MODE                 varchar(40)          NULL,
                      PORT_STATE                     varchar(40)          NULL,
                      RESOURCE_STATE                 varchar(40)          NULL,
                      TRANSPORT_STATE                varchar(40)          NULL,
                      CARRIER_NAME                   varchar(40)          NULL,
                      TRANSPORT_JOB_ID               bigint               NULL,
                      EVENT_NAME                     varchar(40)          NULL,
                      EVENT_TIME                     datetime2            NULL,
                      EVENT_USER                     varchar(40)          NULL,
                      EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE PORT_HISTORY (
                              ID                             bigint               NOT NULL,
                              EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                              PORT_NAME                      varchar(40)          NOT NULL,
                              PORT_TYPE                      varchar(40)          NULL,
                              DESCRIPTION                    varchar(400)         NULL,
                              CONNECTED_STOCKER              varchar(40)          NULL,
                              TRANSPORT_MODE                 varchar(40)          NULL,
                              PORT_STATE                     varchar(40)          NULL,
                              RESOURCE_STATE                 varchar(40)          NULL,
                              TRANSPORT_STATE                varchar(40)          NULL,
                              CARRIER_NAME                   varchar(40)          NULL,
                              TRANSPORT_JOB_ID               bigint               NULL,
                              EVENT_NAME                     varchar(40)          NULL,
                              EVENT_TIME                     datetime2            NOT NULL,
                              EVENT_USER                     varchar(40)          NULL,
                              EVENT_COMMENT                  varchar(100)         NULL
);

CREATE TABLE PRODUCTION_ORDER (
                                  ID                             bigint               NOT NULL,
                                  ORDER_ID                       varchar(40)          NOT NULL,
                                  ORDER_LINE_NUMBER              varchar(40)          NULL,
                                  LOT_NAME                       varchar(40)          NULL,
                                  DESCRIPTION                    varchar(40)          NULL,
                                  ITEM_NAME                      varchar(40)          NULL,
                                  RECIPE_NAME                    varchar(40)          NULL,
                                  CARRIER_NAME                   varchar(40)          NULL,
                                  IDOC_ID                        bigint               NULL,
                                  H2_ORDER_DP_LINE_ID            bigint               NULL,
                                  H2_TRANSP_LINE_ID              bigint               NULL,
                                  GAL_KEY                        varchar(40)          NULL,
                                  MNG_KEY                        bigint               NULL,
                                  PRODUCTION_ORDER_TYPE          varchar(40)          NULL,
                                  PRODUCTION_ORDER_STATE         varchar(40)          NULL,
                                  REPORT_STATE                   varchar(40)          NULL,
                                  HOLD_STATE                     varchar(40)          NULL,
                                  REASON_CODE                    varchar(40)          NULL,
                                  EQUIPMENT_NAME                 varchar(40)          NULL,
                                  PLAN_QUANTITY                  NUMERIC(15 , 3)      NULL,
                                  RELEASED_QUANTITY              NUMERIC(15 , 3)      NULL,
                                  STARTED_QUANTITY               NUMERIC(15 , 3)      NULL,
                                  ENDED_QUANTITY                 NUMERIC(15 , 3)      NULL,
                                  SCRAPPED_QUANTITY              NUMERIC(15 , 3)      NULL,
                                  CREATE_TIME                    datetime2            NULL,
                                  RELEASE_TIME                   datetime2            NULL,
                                  COMPLETE_TIME                  datetime2            NULL,
                                  VALIDATION_TIME                datetime2            NULL,
                                  CREATE_USER                    varchar(40)          NULL,
                                  RELEASE_USER                   varchar(40)          NULL,
                                  COMPLETE_USER                  varchar(40)          NULL,
                                  DUE_DATE                       datetime2            NULL,
                                  EVENT_NAME                     varchar(40)          NULL,
                                  EVENT_TIME                     datetime2            NULL,
                                  EVENT_USER                     varchar(40)          NULL,
                                  EVENT_COMMENT                  varchar(40)          NULL
);

CREATE TABLE PRODUCTION_ORDER_HISTORY (
                                          ID                             bigint               NOT NULL,
                                          ORDER_ID                       varchar(40)          NOT NULL,
                                          ORDER_LINE_NUMBER              varchar(40)          NULL,
                                          LOT_NAME                       varchar(40)          NULL,
                                          DESCRIPTION                    varchar(40)          NULL,
                                          ITEM_NAME                      varchar(40)          NULL,
                                          RECIPE_NAME                    varchar(40)          NULL,
                                          CARRIER_NAME                   varchar(40)          NULL,
                                          IDOC_ID                        bigint               NULL,
                                          H2_ORDER_DP_LINE_ID            bigint               NULL,
                                          H2_TRANSP_LINE_ID              bigint               NULL,
                                          GAL_KEY                        varchar(40)          NULL,
                                          MNG_KEY                        bigint               NULL,
                                          PRODUCTION_ORDER_TYPE          varchar(40)          NULL,
                                          PRODUCTION_ORDER_STATE         varchar(40)          NULL,
                                          REPORT_STATE                   varchar(40)          NULL,
                                          HOLD_STATE                     varchar(40)          NULL,
                                          REASON_CODE                    varchar(40)          NULL,
                                          EQUIPMENT_NAME                 varchar(40)          NULL,
                                          PLAN_QUANTITY                  NUMERIC(15 , 3)      NULL,
                                          RELEASED_QUANTITY              NUMERIC(15 , 3)      NULL,
                                          STARTED_QUANTITY               NUMERIC(15 , 3)      NULL,
                                          ENDED_QUANTITY                 NUMERIC(15 , 3)      NULL,
                                          SCRAPPED_QUANTITY              NUMERIC(15 , 3)      NULL,
                                          CREATE_TIME                    datetime2            NULL,
                                          RELEASE_TIME                   datetime2            NULL,
                                          COMPLETE_TIME                  datetime2            NULL,
                                          VALIDATION_TIME                datetime2            NULL,
                                          CREATE_USER                    varchar(40)          NULL,
                                          RELEASE_USER                   varchar(40)          NULL,
                                          COMPLETE_USER                  varchar(40)          NULL,
                                          DUE_DATE                       datetime2            NULL,
                                          EVENT_NAME                     varchar(40)          NULL,
                                          EVENT_TIME                     datetime2            NULL,
                                          EVENT_USER                     varchar(40)          NULL,
                                          EVENT_COMMENT                  varchar(40)          NULL
);

CREATE TABLE STAT_EQP_AVAILABILITY_HOURLY (
                                              ID                             bigint               NOT NULL,
                                              STAT_DATE                      varchar(10)          NOT NULL,
                                              STAT_HOUR                      varchar(2)           NOT NULL,
                                              EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                                              RUN_DURATION_SEC               int                  NULL,
                                              IDLE_DURATION_SEC              int                  NULL,
                                              DOWN_DURATION_SEC              int                  NULL,
                                              PM_DURATION_SEC                int                  NULL,
                                              ALARM_COUNT                    int                  NULL,
                                              CREATE_TIME                    datetime2            NULL
);

CREATE TABLE STAT_EQP_PRODUCTIVITY_DAILY (
                                             ID                             bigint               NOT NULL,
                                             STAT_DATE                      varchar(10)          NOT NULL,
                                             EQUIPMENT_NAME                 varchar(40)          NOT NULL,
                                             TOTAL_PROCESSED_COUNT          int                  NULL,
                                             TOTAL_PROCESSED_QUANTITY       NUMERIC(15 , 3)      NULL,
                                             OK_PROCESSED                   NUMERIC(15 , 3)      NULL,
                                             NG_PROCESSED                   NUMERIC(15 , 3)      NULL,
                                             AVG_PROCESSED_TIME             int                  NULL
);

CREATE TABLE STAT_TRANSPORT_ROUTE_DAILY (
                                            ID                             bigint               NOT NULL,
                                            STAT_DATE                      varchar(10)          NOT NULL,
                                            SOURCE_EQUIPMENT_NAME          varchar(40)          NOT NULL,
                                            DESTINATION_EQUIPMENT_NAME     varchar(40)          NOT NULL,
                                            TOTAL_COUNT                    int                  NULL,
                                            ERROR_COUNT                    int                  NULL,
                                            AVG_ACQUIRE_TIME_SEC           int                  NULL,
                                            MAX_ACQUIRE_TIME_SEC           int                  NULL,
                                            AVG_TRANSFER_TIME_SEC          int                  NULL,
                                            MAX_TRANSFER_TIME_SEC          int                  NULL,
                                            AVG_CYCLE_TIME_SEC             int                  NULL,
                                            MAX_CYCLE_TIME_SEC             int                  NULL
);

CREATE TABLE STAT_WORK_ORDER_PROCESSED_DAILY (
                                                 ID                             bigint               NOT NULL,
                                                 STAT_DATE                      varchar(10)          NOT NULL,
                                                 TOTAL_PROCESSED_COUNT          int                  NULL,
                                                 AVG_PROCESSED_TIME             int                  NULL,
                                                 TOTAL_QUANTITY                 NUMERIC(15 , 3)      NULL
);

CREATE TABLE TRANSPORT_JOB (
                               ID                             bigint               NOT NULL,
                               TRANSPORT_JOB_NAME             varchar(40)          NOT NULL,
                               TRANSPORT_TYPE                 varchar(40)          NOT NULL,
                               CARRIER_NAME                   varchar(40)          NOT NULL,
                               TRANSPORT_JOB_STATE            varchar(40)          NULL,
                               CARRIER_TYPE                   varchar(40)          NULL,
                               TRAVEL_PROFILE                 varchar(40)          NULL,
                               SOURCE_EQUIPMENT_NAME          varchar(40)          NULL,
                               SOURCE_PORT_NAME               varchar(40)          NULL,
                               SOURCE_ZONE_NAME               varchar(40)          NULL,
                               SOURCE_POSITION_TYPE_NAME      varchar(40)          NULL,
                               SOURCE_POSITION_NAME           varchar(40)          NULL,
                               DESTINATION_EQUIPMENT_NAME     varchar(40)          NULL,
                               DESTINATION_PORT_NAME          varchar(40)          NULL,
                               DESTINATION_ZONE_NAME          varchar(40)          NULL,
                               DESTINATION_POSITION_TYPE_NAME varchar(40)          NULL,
                               DESTINATION_POSITION_NAME      varchar(40)          NULL,
                               PRIORITY                       int                  NULL,
                               ERROR_CODE                     varchar(40)          NULL,
                               ERROR_TEXT                     varchar(250)         NULL,
                               REQUEST_SOURCE                 varchar(40)          NULL,
                               CREATE_TIME                    datetime2            NULL,
                               DEPARTED_TIME                  datetime2            NULL,
                               ARRIVED_TIME                   datetime2            NULL,
                               REASON_CODE                    varchar(40)          NULL,
                               EVENT_NAME                     varchar(40)          NULL,
                               EVENT_TIME                     datetime2            NULL,
                               EVENT_USER                     varchar(40)          NULL,
                               EVENT_COMMENT                  varchar(250)         NULL,
                               ORDER_ID                       varchar(40)          NULL
);

CREATE TABLE TRANSPORT_JOB_HISTORY (
                                       ID                             bigint               NOT NULL,
                                       TRANSPORT_JOB_NAME             varchar(40)          NOT NULL,
                                       TRANSPORT_TYPE                 varchar(40)          NOT NULL,
                                       CARRIER_NAME                   varchar(40)          NOT NULL,
                                       TRANSPORT_JOB_STATE            varchar(40)          NULL,
                                       CARRIER_TYPE                   varchar(40)          NULL,
                                       TRAVEL_PROFILE                 varchar(40)          NULL,
                                       SOURCE_EQUIPMENT_NAME          varchar(40)          NULL,
                                       SOURCE_PORT_NAME               varchar(40)          NULL,
                                       SOURCE_ZONE_NAME               varchar(40)          NULL,
                                       SOURCE_POSITION_TYPE_NAME      varchar(40)          NULL,
                                       SOURCE_POSITION_NAME           varchar(40)          NULL,
                                       DESTINATION_EQUIPMENT_NAME     varchar(40)          NULL,
                                       DESTINATION_PORT_NAME          varchar(40)          NULL,
                                       DESTINATION_ZONE_NAME          varchar(40)          NULL,
                                       DESTINATION_POSITION_TYPE_NAME varchar(40)          NULL,
                                       DESTINATION_POSITION_NAME      varchar(40)          NULL,
                                       PRIORITY                       int                  NULL,
                                       ERROR_CODE                     varchar(40)          NULL,
                                       ERROR_TEXT                     varchar(250)         NULL,
                                       REQUEST_SOURCE                 varchar(40)          NULL,
                                       CREATE_TIME                    datetime2            NULL,
                                       DEPARTED_TIME                  datetime2            NULL,
                                       ARRIVED_TIME                   datetime2            NULL,
                                       REASON_CODE                    varchar(40)          NULL,
                                       EVENT_NAME                     varchar(40)          NULL,
                                       EVENT_TIME                     datetime2            NOT NULL,
                                       EVENT_USER                     varchar(40)          NULL,
                                       EVENT_COMMENT                  varchar(250)         NULL,
                                       ORDER_ID                       varchar(40)          NULL
);

CREATE TABLE TRANSPORT_ORDER (
                                 ID                             bigint               NOT NULL,
                                 TRANSPORT_ORDER_ID             varchar(40)          NULL,
                                 IDOC_ID                        varchar(40)          NULL,
                                 DESCRIPTION                    varchar(40)          NULL,
                                 CARRIER_NAME                   varchar(40)          NULL,
                                 VIRTUAL_CARRIER_NAME           varchar(40)          NULL,
                                 TRANSPORT_TYPE                 varchar(40)          NULL,
                                 TRANSPORT_STATUS               varchar(40)          NULL,
                                 LAST_TRANSACTION_CODE          varchar(40)          NULL,
                                 CARRIER_TYPE                   varchar(40)          NULL,
                                 PRIORITY                       int                  NULL,
                                 GAL_ID                         varchar(40)          NULL,
                                 GAL_WAREHOUSE                  varchar(40)          NULL,
                                 LOCATION_ID                    varchar(40)          NULL,
                                 WORK_STATION_ID                varchar(40)          NULL,
                                 SOURCE_ZONE_NAME               varchar(40)          NULL,
                                 DESTINATION_ZONE_NAME          varchar(40)          NULL,
                                 ERROR_TEXT                     varchar(40)          NULL,
                                 ACTUAL_WEIGHT                  varchar(40)          NULL,
                                 REQUESTED_ZONE_NAME            varchar(40)          NULL,
                                 ACTUAL_ZONE_NAME               varchar(40)          NULL,
                                 ACTUAL_LOCATION_ID             varchar(40)          NULL,
                                 TRAVEL_PROFILE                 varchar(40)          NULL,
                                 CREATE_TIME                    datetime2            NULL,
                                 RELEASE_TIME                   datetime2            NULL,
                                 COMPLETE_TIME                  datetime2            NULL,
                                 RETRIEVAL_TIME                 datetime2            NULL,
                                 CREATE_USER                    varchar(40)          NULL,
                                 RELEASE_USER                   varchar(40)          NULL,
                                 COMPLETE_USER                  varchar(40)          NULL,
                                 EVENT_NAME                     varchar(40)          NULL,
                                 EVENT_TIME                     datetime2            NULL,
                                 EVENT_USER                     varchar(40)          NULL,
                                 EVENT_COMMENT                  varchar(40)          NULL
);

CREATE TABLE TRANSPORT_ORDER_HISTORY (
                                         ID                             bigint               NOT NULL,
                                         TRANSPORT_ORDER_ID             varchar(40)          NULL,
                                         IDOC_ID                        varchar(40)          NULL,
                                         DESCRIPTION                    varchar(40)          NULL,
                                         CARRIER_NAME                   varchar(40)          NULL,
                                         VIRTUAL_CARRIER_NAME           varchar(40)          NULL,
                                         TRANSPORT_TYPE                 varchar(40)          NULL,
                                         TRANSPORT_STATUS               varchar(40)          NULL,
                                         LAST_TRANSACTION_CODE          varchar(40)          NULL,
                                         CARRIER_TYPE                   varchar(40)          NULL,
                                         PRIORITY                       int                  NULL,
                                         GAL_ID                         varchar(40)          NULL,
                                         GAL_WAREHOUSE                  varchar(40)          NULL,
                                         LOCATION_ID                    varchar(40)          NULL,
                                         WORK_STATION_ID                varchar(40)          NULL,
                                         SOURCE_ZONE_NAME               varchar(40)          NULL,
                                         DESTINATION_ZONE_NAME          varchar(40)          NULL,
                                         ERROR_TEXT                     varchar(40)          NULL,
                                         ACTUAL_WEIGHT                  varchar(40)          NULL,
                                         REQUESTED_ZONE_NAME            varchar(40)          NULL,
                                         ACTUAL_ZONE_NAME               varchar(40)          NULL,
                                         ACTUAL_LOCATION_ID             varchar(40)          NULL,
                                         TRAVEL_PROFILE                 varchar(40)          NULL,
                                         CREATE_TIME                    datetime2            NULL,
                                         RELEASE_TIME                   datetime2            NULL,
                                         COMPLETE_TIME                  datetime2            NULL,
                                         RETRIEVAL_TIME                 datetime2            NULL,
                                         CREATE_USER                    varchar(40)          NULL,
                                         RELEASE_USER                   varchar(40)          NULL,
                                         COMPLETE_USER                  varchar(40)          NULL,
                                         EVENT_NAME                     varchar(40)          NULL,
                                         EVENT_TIME                     datetime2            NULL,
                                         EVENT_USER                     varchar(40)          NULL,
                                         EVENT_COMMENT                  varchar(40)          NULL
);


-- MNG